<?php

$reqCreationRecharge = "CREATE TABLE public.data_recharge_$valFacial
(
  numero bigint NOT NULL,
  total_j1 integer DEFAULT 0,
  total_j2 integer DEFAULT 0,
  total_j3 integer DEFAULT 0,
  total_j4 integer DEFAULT 0,
  total_j5 integer DEFAULT 0,
  total_j6 integer DEFAULT 0,
  total_j7 integer DEFAULT 0,
  total_j8 integer DEFAULT 0,
  total_j9 integer DEFAULT 0,
  total_j10 integer DEFAULT 0,
  total_j11 integer DEFAULT 0,
  total_j12 integer DEFAULT 0,
  total_j13 integer DEFAULT 0,
  total_j14 integer DEFAULT 0,
  total_j15 integer DEFAULT 0,
  total_j16 integer DEFAULT 0,
  total_j17 integer DEFAULT 0,
  total_j18 integer DEFAULT 0,
  total_j19 integer DEFAULT 0,
  total_j20 integer DEFAULT 0,
  total_j21 integer DEFAULT 0,
  total_j22 integer DEFAULT 0,
  total_j23 integer DEFAULT 0,
  total_j24 integer DEFAULT 0,
  total_j25 integer DEFAULT 0,
  total_j26 integer DEFAULT 0,
  total_j27 integer DEFAULT 0,
  total_j28 integer DEFAULT 0,
  total_j29 integer DEFAULT 0,
  total_j30 integer DEFAULT 0,
  total_j31 integer DEFAULT 0,
  total_j32 integer DEFAULT 0,
  total_m1 integer DEFAULT 0,
  total_m2 integer DEFAULT 0,
  total_m3 integer DEFAULT 0,
  total_m4 integer DEFAULT 0,
  total_m5 integer DEFAULT 0,
  total_m6 integer DEFAULT 0,
  total_m7 integer DEFAULT 0,
  total_m8 integer DEFAULT 0,
  total_m9 integer DEFAULT 0,
  total_m10 integer DEFAULT 0,
  total_m11 integer DEFAULT 0,
  total_m12 integer DEFAULT 0,
  total_m13 integer DEFAULT 0,
  total_a1 bigint DEFAULT 0,
  total_a2 bigint DEFAULT 0,
  total_a3 bigint DEFAULT 0,
  total_a4 bigint DEFAULT 0,
  total_a5 bigint DEFAULT 0,
  ivr_j1 integer DEFAULT 0,
  ivr_j2 integer DEFAULT 0,
  ivr_j3 integer DEFAULT 0,
  ivr_j4 integer DEFAULT 0,
  ivr_j5 integer DEFAULT 0,
  ivr_j6 integer DEFAULT 0,
  ivr_j7 integer DEFAULT 0,
  ivr_j8 integer DEFAULT 0,
  ivr_j9 integer DEFAULT 0,
  ivr_j10 integer DEFAULT 0,
  ivr_j11 integer DEFAULT 0,
  ivr_j12 integer DEFAULT 0,
  ivr_j13 integer DEFAULT 0,
  ivr_j14 integer DEFAULT 0,
  ivr_j15 integer DEFAULT 0,
  ivr_j16 integer DEFAULT 0,
  ivr_j17 integer DEFAULT 0,
  ivr_j18 integer DEFAULT 0,
  ivr_j19 integer DEFAULT 0,
  ivr_j20 integer DEFAULT 0,
  ivr_j21 integer DEFAULT 0,
  ivr_j22 integer DEFAULT 0,
  ivr_j23 integer DEFAULT 0,
  ivr_j24 integer DEFAULT 0,
  ivr_j25 integer DEFAULT 0,
  ivr_j26 integer DEFAULT 0,
  ivr_j27 integer DEFAULT 0,
  ivr_j28 integer DEFAULT 0,
  ivr_j29 integer DEFAULT 0,
  ivr_j30 integer DEFAULT 0,
  ivr_j31 integer DEFAULT 0,
  ivr_j32 integer DEFAULT 0,
  ivr_m1 integer DEFAULT 0,
  ivr_m2 integer DEFAULT 0,
  ivr_m3 integer DEFAULT 0,
  ivr_m4 integer DEFAULT 0,
  ivr_m5 integer DEFAULT 0,
  ivr_m6 integer DEFAULT 0,
  ivr_m7 integer DEFAULT 0,
  ivr_m8 integer DEFAULT 0,
  ivr_m9 integer DEFAULT 0,
  ivr_m10 integer DEFAULT 0,
  ivr_m11 integer DEFAULT 0,
  ivr_m12 integer DEFAULT 0,
  ivr_m13 integer DEFAULT 0,
  ivr_a1 bigint DEFAULT 0,
  ivr_a2 bigint DEFAULT 0,
  ivr_a3 bigint DEFAULT 0,
  ivr_a4 bigint DEFAULT 0,
  ivr_a5 bigint DEFAULT 0,
  sms_j1 integer DEFAULT 0,
  sms_j2 integer DEFAULT 0,
  sms_j3 integer DEFAULT 0,
  sms_j4 integer DEFAULT 0,
  sms_j5 integer DEFAULT 0,
  sms_j6 integer DEFAULT 0,
  sms_j7 integer DEFAULT 0,
  sms_j8 integer DEFAULT 0,
  sms_j9 integer DEFAULT 0,
  sms_j10 integer DEFAULT 0,
  sms_j11 integer DEFAULT 0,
  sms_j12 integer DEFAULT 0,
  sms_j13 integer DEFAULT 0,
  sms_j14 integer DEFAULT 0,
  sms_j15 integer DEFAULT 0,
  sms_j16 integer DEFAULT 0,
  sms_j17 integer DEFAULT 0,
  sms_j18 integer DEFAULT 0,
  sms_j19 integer DEFAULT 0,
  sms_j20 integer DEFAULT 0,
  sms_j21 integer DEFAULT 0,
  sms_j22 integer DEFAULT 0,
  sms_j23 integer DEFAULT 0,
  sms_j24 integer DEFAULT 0,
  sms_j25 integer DEFAULT 0,
  sms_j26 integer DEFAULT 0,
  sms_j27 integer DEFAULT 0,
  sms_j28 integer DEFAULT 0,
  sms_j29 integer DEFAULT 0,
  sms_j30 integer DEFAULT 0,
  sms_j31 integer DEFAULT 0,
  sms_j32 integer DEFAULT 0,
  sms_m1 integer DEFAULT 0,
  sms_m2 integer DEFAULT 0,
  sms_m3 integer DEFAULT 0,
  sms_m4 integer DEFAULT 0,
  sms_m5 integer DEFAULT 0,
  sms_m6 integer DEFAULT 0,
  sms_m7 integer DEFAULT 0,
  sms_m8 integer DEFAULT 0,
  sms_m9 integer DEFAULT 0,
  sms_m10 integer DEFAULT 0,
  sms_m11 integer DEFAULT 0,
  sms_m12 integer DEFAULT 0,
  sms_m13 integer DEFAULT 0,
  sms_a1 bigint DEFAULT 0,
  sms_a2 bigint DEFAULT 0,
  sms_a3 bigint DEFAULT 0,
  sms_a4 bigint DEFAULT 0,
  sms_a5 bigint DEFAULT 0,
  ussd_j1 integer DEFAULT 0,
  ussd_j2 integer DEFAULT 0,
  ussd_j3 integer DEFAULT 0,
  ussd_j4 integer DEFAULT 0,
  ussd_j5 integer DEFAULT 0,
  ussd_j6 integer DEFAULT 0,
  ussd_j7 integer DEFAULT 0,
  ussd_j8 integer DEFAULT 0,
  ussd_j9 integer DEFAULT 0,
  ussd_j10 integer DEFAULT 0,
  ussd_j11 integer DEFAULT 0,
  ussd_j12 integer DEFAULT 0,
  ussd_j13 integer DEFAULT 0,
  ussd_j14 integer DEFAULT 0,
  ussd_j15 integer DEFAULT 0,
  ussd_j16 integer DEFAULT 0,
  ussd_j17 integer DEFAULT 0,
  ussd_j18 integer DEFAULT 0,
  ussd_j19 integer DEFAULT 0,
  ussd_j20 integer DEFAULT 0,
  ussd_j21 integer DEFAULT 0,
  ussd_j22 integer DEFAULT 0,
  ussd_j23 integer DEFAULT 0,
  ussd_j24 integer DEFAULT 0,
  ussd_j25 integer DEFAULT 0,
  ussd_j26 integer DEFAULT 0,
  ussd_j27 integer DEFAULT 0,
  ussd_j28 integer DEFAULT 0,
  ussd_j29 integer DEFAULT 0,
  ussd_j30 integer DEFAULT 0,
  ussd_j31 integer DEFAULT 0,
  ussd_j32 integer DEFAULT 0,
  ussd_m1 integer DEFAULT 0,
  ussd_m2 integer DEFAULT 0,
  ussd_m3 integer DEFAULT 0,
  ussd_m4 integer DEFAULT 0,
  ussd_m5 integer DEFAULT 0,
  ussd_m6 integer DEFAULT 0,
  ussd_m7 integer DEFAULT 0,
  ussd_m8 integer DEFAULT 0,
  ussd_m9 integer DEFAULT 0,
  ussd_m10 integer DEFAULT 0,
  ussd_m11 integer DEFAULT 0,
  ussd_m12 integer DEFAULT 0,
  ussd_m13 integer DEFAULT 0,
  ussd_a1 bigint DEFAULT 0,
  ussd_a2 bigint DEFAULT 0,
  ussd_a3 bigint DEFAULT 0,
  ussd_a4 bigint DEFAULT 0,
  ussd_a5 bigint DEFAULT 0,
  CONSTRAINT data_recharge_".$valFacial."_pkey PRIMARY KEY (numero)
)
WITH (
  OIDS=FALSE
)
";
 
 try{
	$result = $connection->query($reqCreationRecharge);
}
catch(PDOException $e){
	echo $e->getMessage();
	// print_r($e);
	// die();
}

$rqInsertAllNum = 'INSERT INTO data_recharge_'.$valFacial.' (numero) SELECT numero FROM data_attribut';
 try{
	$result = $connection->query($rqInsertAllNum);
}
catch(PDOException $e){
	echo $e->getMessage();
}
?>